#!/usr/bin/env bash
# Prints the full Basemate skill documentation
set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "=============================================="
echo "  🔗 BASEMATE — Group Discovery for XMTP"
echo "  Full Skill Documentation"
echo "=============================================="
echo ""

cat "$DIR/SKILL.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Agent Setup"
echo "=============================================="
echo ""
cat "$DIR/references/agent-setup.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Discovery"
echo "=============================================="
echo ""
cat "$DIR/references/discovery.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Create a Group"
echo "=============================================="
echo ""
cat "$DIR/references/create-group.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Boost"
echo "=============================================="
echo ""
cat "$DIR/references/boost.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Auction"
echo "=============================================="
echo ""
cat "$DIR/references/auction.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Messaging & Content Types"
echo "=============================================="
echo ""
cat "$DIR/references/messaging.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Inline Actions (Buttons)"
echo "=============================================="
echo ""
cat "$DIR/references/inline-actions.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: USDC Transfers (In-Chat)"
echo "=============================================="
echo ""
cat "$DIR/references/transactions.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Reactions"
echo "=============================================="
echo ""
cat "$DIR/references/reactions.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Group Management"
echo "=============================================="
echo ""
cat "$DIR/references/group-management.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: Domain Resolution"
echo "=============================================="
echo ""
cat "$DIR/references/domain-resolution.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: DM Basemate"
echo "=============================================="
echo ""
cat "$DIR/references/dm-basemate.md"

echo ""
echo "=============================================="
echo "  📖 REFERENCE: API Reference"
echo "=============================================="
echo ""
cat "$DIR/references/api-reference.md"

echo ""
echo "=============================================="
echo "  ✅ End of Basemate Skill Docs"
echo "=============================================="
